In [1]:
import numpy as np # Linear algebra
import pandas as pd # Data processing
from sklearn.preprocessing import LabelEncoder # If data isstring then

from sklearn.tree import DecisionTreeClassifier
df = pd.read_csv('/content/sample_data/glass.csv')
df

1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.00.1  1
0    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00    0.00  1
1    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00    0.00  1
2    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00    0.00  1
3    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00    0.00  1
4    1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00    0.26  1
..       ...    ...   ...   ...    ...   ...   ...   ...     ... ..
208  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06    0.00  7
209  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59    0.00  7
210  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64    0.00  7
211  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57    0.00  7
212  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67    0.00  7

[213 rows x 10 columns]

In [2]:
# Extracting Features
X = df.iloc[:,:-1]
y= df.iloc[:,9]
# Making Model
dt = DecisionTreeClassifier(criterion = "entropy")
dt
DecisionTreeClassifier(criterion='entropy')
# Splitting the dataset into training, testing and predicting values:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [3]:
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
y_pred

array([7, 1, 1, 5, 2, 2, 1, 2, 1, 7, 1, 1, 3, 1, 2, 7, 2, 1, 1, 3, 6, 7,
       7, 7, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 3, 2, 7, 2, 6, 2, 2,
       1, 1, 1, 2, 2, 2, 1, 5, 7, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2])

In [9]:
# Making Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[14  6  0  0  0  0]
 [ 7 16  0  1  0  1]
 [ 3  2  3  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  7]]


**Accuracy of ID3**

In [10]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0
for row in range(a[0]):
  for c in range(a[1]):
    if row == c:
      corrPred += cm[row,c]
    else:
      falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the ID3 is: ', corrPred/(cm.sum()))


Correct predictions:  43
False predictions 21


Accuracy of the ID3 is:  0.671875


In [13]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
iris = load_iris()

In [14]:
decision_tree = DecisionTreeClassifier(random_state=0, max_depth=2)
decision_tree = decision_tree.fit(iris.data, iris.target)

In [15]:
r = export_text(decision_tree, feature_names = iris['feature_names'])
print(r)

|--- petal width (cm) <= 0.80
|   |--- class: 0
|--- petal width (cm) >  0.80
|   |--- petal width (cm) <= 1.75
|   |   |--- class: 1
|   |--- petal width (cm) >  1.75
|   |   |--- class: 2



In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn.datasets import load_iris
iris = load_iris()


In [18]:
X = iris.data
y = iris.target
dataset = pd.read_csv('/content/sample_data/golf-dataset.csv')
dataset.head()

Outlook  Temp Humidity  Windy Play Golf
0     Rainy   Hot     High  False        No
1     Rainy   Hot     High   True        No
2  Overcast   Hot     High  False       Yes
3     Sunny  Mild     High  False       Yes
4     Sunny  Cool   Normal  False       Yes

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.4, random_state=1)

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
GaussianNB()

GaussianNB()

In [22]:
# making predictions on the testing set
y_pred = gnb.predict(X_test)
print(y_pred)

[0 1 1 0 2 2 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 1 2 1 2 0 0 0 1 0 0 2 2 2 2 2 1 2 1]


In [23]:
y_compare = np.vstack((y_test,y_pred)).T
y_compare[:5,:]

array([[0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [2, 2]])

In [24]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

a = cm.shape
corrPred = 0
falsePred = 0

[[19  0  0]
 [ 0 19  2]
 [ 0  1 19]]


In [25]:
for row in range(a[0]):
  for c in range(a[1]):
    if row == c:
      corrPred +=cm[row,c]
    else:
      falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ',
corrPred/(cm.sum()))

Correct predictions:  57
False predictions 3


Accuracy of the Naive Bayes Clasification is:  0.95
