Name- Shubham Nikam
Class- FYMCA
Roll no - 32

In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
Model = LinearRegression()
Model

LinearRegression()

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(20).reshape((10,2)),range(10)
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [4]:
list(y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=30)

In [6]:
X_train

array([[12, 13],
       [ 8,  9],
       [14, 15],
       [16, 17],
       [18, 19],
       [10, 11]])

In [7]:
y_train

[6, 4, 7, 8, 9, 5]

In [8]:
X_test

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
y_test

[0, 1, 2, 3]

In [10]:
train_test_split(y,shuffle=False)

[[0, 1, 2, 3, 4, 5, 6], [7, 8, 9]]

In [11]:
Model.fit(X_train,y_train)

LinearRegression()

In [12]:
predictions = Model.predict(X_test)

In [13]:
predictions

array([3.44169138e-15, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00])